#!/usr/bin/env node
/**
 * Creates or updates .env.local with the administrator credentials and a
 * session secret. Run it once after cloning:
 *
 *   npm run setup
 *   npm run setup -- --username admin --password "your password"
 */
import { randomBytes } from "node:crypto";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { createInterface } from "node:readline/promises";
import { stdin, stdout } from "node:process";
import bcrypt from "bcryptjs";

const ENV_PATH = new URL("../.env.local", import.meta.url);

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === "--username") args.username = argv[i + 1];
    if (argv[i] === "--password") args.password = argv[i + 1];
  }
  return args;
}

function readExisting() {
  if (!existsSync(ENV_PATH)) return {};
  const values = {};
  for (const line of readFileSync(ENV_PATH, "utf8").split(/\r?\n/)) {
    const match = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (match) values[match[1]] = match[2].replace(/^"|"$/g, "");
  }
  return values;
}

const args = parseArgs(process.argv.slice(2));
const existing = readExisting();

let username = args.username;
let password = args.password;

if (!username || !password) {
  const rl = createInterface({ input: stdin, output: stdout });
  try {
    if (!username) {
      const answer = await rl.question(
        `Administrator username [${existing.ADMIN_USERNAME || "admin"}]: `,
      );
      username = answer.trim() || existing.ADMIN_USERNAME || "admin";
    }
    if (!password) {
      // Note: the password is echoed. This runs locally during setup only.
      password = (await rl.question("Administrator password: ")).trim();
    }
  } finally {
    rl.close();
  }
}

if (!password || password.length < 8) {
  console.error("\nPassword must be at least 8 characters. Nothing was written.");
  process.exit(1);
}

const passwordHash = bcrypt.hashSync(password, 12);
// Next.js expands `$NAME` inside .env values, which would eat the `$2b$12$...`
// separators in a bcrypt hash. Escaping each `$` keeps the hash intact.
const escapedHash = passwordHash.replace(/\$/g, "\\$");
const sessionSecret =
  existing.SESSION_SECRET && existing.SESSION_SECRET.length >= 32
    ? existing.SESSION_SECRET
    : randomBytes(48).toString("base64url");

const contents = `# Generated by \`npm run setup\`. Do not commit this file.

# Local SQLite file. For production, point this at your Turso database URL
# (libsql://...) and set DATABASE_AUTH_TOKEN.
DATABASE_URL="${existing.DATABASE_URL || "file:./data/app.db"}"
DATABASE_AUTH_TOKEN="${existing.DATABASE_AUTH_TOKEN || ""}"

# Signs the administrator session cookie. Changing it signs everyone out.
SESSION_SECRET="${sessionSecret}"

# The single administrator account. Each \$ in the bcrypt hash is escaped
# because Next.js expands \$NAME inside .env files.
ADMIN_USERNAME="${username}"
ADMIN_PASSWORD_HASH="${escapedHash}"

# Country pre-selected in the student application form (ISO code).
NEXT_PUBLIC_DEFAULT_COUNTRY="${existing.NEXT_PUBLIC_DEFAULT_COUNTRY || "MY"}"
`;

writeFileSync(ENV_PATH, contents, "utf8");

console.log(`\n✅ Wrote .env.local`);
console.log(`   Administrator username: ${username}`);
console.log(`\nStart the app with:  npm run dev`);
console.log(`Then sign in at:     http://localhost:3000/admin`);
console.log(
  `\nWhen deploying, paste these UNESCAPED values into your host's env settings:`,
);
console.log(`   ADMIN_PASSWORD_HASH = ${passwordHash}`);
console.log(`   SESSION_SECRET      = ${sessionSecret}\n`);
